### ISSUE TITLE
Design/implement separate accounts per experimenter

### ISSUE THREAD

**Issue by cjqian** [PAIR-code/deliberate-lab#98]
Idea: experiments are tied to a single experimenter (no concept of sharing across teams) for simplicity.

Consideration: what if you'd like to share an experiment view with someone else (e.g. sharing playtest results)? For now, should be fine to share a link of a participant's view after the game.

**Comment by cjqian** [comment]
From the document:

"We can easily configure experiment visibility with additional fields in experiment documents + additional experimenter custom claims (auth), but changing custom claims can be tedious so we should plan what logic we want.
"

@LeoLaugier @GnRlLeclerc Not sure which one of you added the comment above; could you expand on what `custom claims` are?

**Comment by GnRlLeclerc** [comment]
> From the document:
> 
> "We can easily configure experiment visibility with additional fields in experiment documents + additional experimenter custom claims (auth), but changing custom claims can be tedious so we should plan what logic we want. "
> 
> @LeoLaugier @GnRlLeclerc Not sure which one of you added the comment above; could you expand on what `custom claims` are?

Custom claims are a JSON object that we can associate to a specific user in order to specify more information about them. The user cannot change them.

Right now, "granting experimenter rights" is equivalent to setting a logged-in user's custom claims to `{ "role": "experimenter" }`.

This can easily be done in development using the emulators, but is harder to do in production.

Examples:

- [Checking user custom claims in the frontend](https://github.com/PAIR-code/llm-mediation-experiments/blob/13b7588ddb73a5c92000c6e8c7ed12ebcef2ed04/lit/src/services/auth_service.ts#L31)
- [Setting user custom claims](https://github.com/PAIR-code/llm-mediation-experiments/blob/13b7588ddb73a5c92000c6e8c7ed12ebcef2ed04/scripts/src/set-experimenter.ts#L25)

**Comment by vivtsai** [comment]
Fixed by refactor
